# importing the needed lib

In [5]:
import numpy as np

In [6]:
import pandas as pd

## data showcase

In [26]:
data = pd.read_csv('./tmdb-movies.csv')

###### movies data showcase

In [96]:
data.head(5)

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/15,5562,6.5,2015,1.379999e+08,1.392446e+09
1,76341,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,...,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/15,6185,7.1,2015,1.379999e+08,3.481613e+08
2,262500,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,...,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/15,2480,6.3,2015,1.012000e+08,2.716190e+08
3,140607,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,...,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/15,5292,7.5,2015,1.839999e+08,1.902723e+09
4,168259,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,...,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/15,2947,7.3,2015,1.747999e+08,1.385749e+09

## what makes genres succsessful

<img src="https://i.ytimg.com/vi/ScXuVBuWiF8/maxresdefault.jpg" alt="Python Logo" width="400px" height="350px" style="float: left;">

In [184]:
gen_date = data[['release_date', 'genres', 'popularity']]
gen_date_most = gen_date.sort_values(by='release_date', ascending=False)
gen_date.head(50)

   release_date                                           genres  popularity
0        6/9/15        Action|Adventure|Science Fiction|Thriller   32.985763
1       5/13/15        Action|Adventure|Science Fiction|Thriller   28.419936
2       3/18/15               Adventure|Science Fiction|Thriller   13.112507
3      12/15/15         Action|Adventure|Science Fiction|Fantasy   11.173104
4        4/1/15                            Action|Crime|Thriller    9.335014
5      12/25/15                 Western|Drama|Adventure|Thriller    9.110700
6       6/23/15        Science Fiction|Action|Thriller|Adventure    8.654359
7       9/30/15                  Drama|Adventure|Science Fiction    7.667400
8       6/17/15                Family|Animation|Adventure|Comedy    7.404165
9        6/9/15                          Comedy|Animation|Family    6.326804
10     10/26/15                           Action|Adventure|Crime    6.200282
11       2/4/15         Science Fiction|Fantasy|Action|Adventure    6.189369
12      1/21/15                            Drama|Science Fiction    6.118847
13      7/16/15                    Action|Comedy|Science Fiction    5.984995
14      4/22/15                 Action|Adventure|Science Fiction    5.944927
15     12/25/15                      Crime|Drama|Mystery|Western    5.898400
16       1/1/15                            Crime|Action|Thriller    5.749758
17      7/14/15                 Science Fiction|Action|Adventure    5.573184
18      3/12/15                     Romance|Fantasy|Family|Drama    5.556818
19     11/18/15                    War|Adventure|Science Fiction    5.476958
20      5/19/15  Action|Family|Science Fiction|Adventure|Mystery    5.462138
21      6/15/15                                     Action|Drama    5.337064
22      5/27/15                            Action|Drama|Thriller    4.907832
23      2/11/15                                    Drama|Romance    4.710402
24     12/11/15                                     Comedy|Drama    4.648046
25      7/23/15                                           Action    4.566713
26      6/25/15                                           Comedy    4.564549
27      1/24/15                    Crime|Comedy|Action|Adventure    4.503789
28      11/6/15                           Drama|Thriller|History    4.062293
29       9/9/15                  Action|Science Fiction|Thriller    3.968891
30      6/19/15                                    Mystery|Drama    3.927333
31       3/4/15                     Crime|Action|Science Fiction    3.899557
32       5/7/15                                     Comedy|Music    3.877764
33     10/15/15                                   Thriller|Drama    3.648210
34       8/5/15                          Adventure|Horror|Comedy    3.644541
35     10/16/15                                   Drama|Thriller    3.557846
36       9/3/15                              Crime|Drama|Mystery    3.358321
37     11/14/15        Adventure|Animation|Comedy|Family|Fantasy    3.339135
38      3/11/15              Action|Crime|Drama|Mystery|Thriller    3.237370
39      11/4/15                                    Drama|Romance    3.227329
40      8/13/15                                      Drama|Music    3.202719
41     10/21/15                         Fantasy|Action|Adventure    3.080505
42      10/9/15                                    History|Drama    3.079522
43      8/13/15                          Comedy|Action|Adventure    3.053421
44      4/16/15                            Fantasy|Drama|Romance    3.025852
45      9/12/15                 Action|Adventure|Science Fiction    3.023253
46      3/18/15  Fantasy|Comedy|Animation|Science Fiction|Family    2.976436
47       7/9/15                            Drama|Mystery|Romance    2.968254
48      1/14/15                             Thriller|Crime|Drama    2.932340
49      10/8/15    Thriller|Comedy|Drama|Romance|Science Fiction    2.885126

## common indicators of a movie succsess

In [164]:
ass_grouping = data [['original_title', 'cast','director' ,'production_companies','budget','revenue', 'genres', 'release_date']]
ass_grouping

,original_title,cast,director,production_companies,budget,revenue,genres,release_date
0,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,Universal Studios|Amblin Entertainment|Legenda...,150000000,1513528810,Action|Adventure|Science Fiction|Thriller,6/9/15
1,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,Village Roadshow Pictures|Kennedy Miller Produ...,150000000,378436354,Action|Adventure|Science Fiction|Thriller,5/13/15
2,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,Robert Schwentke,Summit Entertainment|Mandeville Films|Red Wago...,110000000,295238201,Adventure|Science Fiction|Thriller,3/18/15
3,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Lucasfilm|Truenorth Productions|Bad Robot,200000000,2068178225,Action|Adventure|Science Fiction|Fantasy,12/15/15
4,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Universal Pictures|Original Film|Media Rights ...,190000000,1506249360,Action|Crime|Thriller,4/1/15
...,...,...,...,...,...,...,...,...
10861,The Endless Summer,Michael Hynson|Robert August|Lord 'Tally Ho' B...,Bruce Brown,Bruce Brown Films,0,0,Documentary,6/15/66
10862,Grand Prix,James Garner|Eva Marie Saint|Yves Montand|Tosh...,John Frankenheimer,Cherokee Productions|Joel Productions|Douglas ...,0,0,Action|Adventure|Drama,12/21/66
10863,Beregis Avtomobilya,Innokentiy Smoktunovskiy|Oleg Efremov|Georgi Z...,Eldar Ryazanov,Mosfilm,0,0,Mystery|Comedy,1/1/66
10864,"What's Up, Tiger Lily?",Tatsuya Mihashi|Akiko Wakabayashi|Mie Hama|Joh...,Woody Allen,Benedict Pictures Corp.,0,0,Action|Comedy,11/2/66
10865,Manos: The Hands of Fate,Harold P. Warren|Tom Neyman|John Reynolds|Dian...,Harold P. Warren,Norm-Iris,19000,0,Horror,11/15/66

## as shown above the movie industry shares a common indicators of success yet there's thousands of movies

### but what are the criterias associated with success, budget\revenue, ratings or popularity

## well let's check the relevance between them and determine what the sucsess factor is 

### starting with cost/revenue analysis to the top 50

In [153]:

cost_rev.loc[:, 'profit'] = cost_rev['revenue'] - cost_rev['budget']
cost_rev_most = cost_rev.sort_values(by='profit', ascending=False)
cost_rev_most.head(50)

,original_title,budget,revenue,profit
1386,Avatar,237000000,2781505847,2544505847
3,Star Wars: The Force Awakens,200000000,2068178225,1868178225
5231,Titanic,200000000,1845034188,1645034188
0,Jurassic World,150000000,1513528810,1363528810
4,Furious 7,190000000,1506249360,1316249360
4361,The Avengers,220000000,1519557910,1299557910
3374,Harry Potter and the Deathly Hallows: Part 2,125000000,1327817822,1202817822
14,Avengers: Age of Ultron,280000000,1405035767,1125035767
5422,Frozen,150000000,1274219009,1124219009
8094,The Net,22000000,1106279658,1084279658
8,Minions,74000000,1156730962,1082730962
4949,The Lord of the Rings: The Return of the King,94000000,1118888979,1024888979
5425,Iron Man 3,200000000,1215439994,1015439994
3522,Transformers: Dark of the Moon,195000000,1123746996,928746996
4365,Skyfall,200000000,1108561013,908561013
5434,Despicable Me 2,76000000,970761885,894761885
6555,Pirates of the Caribbean: Dead Man's Chest,200000000,1065659812,865659812
1930,Toy Story 3,200000000,1063171911,863171911
10223,Jurassic Park,63000000,920100000,857100000
2634,Harry Potter and the Philosopher's Stone,125000000,976475550,851475550
3911,The Lord of the Rings: The Two Towers,79000000,926287400,847287400
4363,The Dark Knight Rises,250000000,1081041287,831041287
1921,Alice in Wonderland,200000000,1025467110,825467110
2875,The Dark Knight,185000000,1001921825,816921825
2412,Star Wars: Episode I - The Phantom Menace,115000000,924317558,809317558
1396,Ice Age: Dawn of the Dinosaurs,90000000,886686817,796686817
7388,Harry Potter and the Order of the Phoenix,150000000,938212738,788212738
8889,E.T. the Extra-Terrestrial,10500000,792910554,782410554
4375,Ice Age: Continental Drift,95000000,877244782,782244782
2633,The Lord of the Rings: The Fellowship of the Ring,93000000,871368364,778368364
3912,Harry Potter and the Chamber of Secrets,100000000,876688482,776688482
4955,Finding Nemo,94000000,864625978,770625978
6977,Shrek 2,150000000,919838758,769838758
4367,The Hobbit: An Unexpected Journey,250000000,1017003568,767003568
1329,Star Wars,11000000,775398007,764398007
6190,Harry Potter and the Goblet of Fire,150000000,895921036,745921036
4180,The Lion King,45000000,788241776,743241776
8457,Independence Day,75000000,816969268,741969268
6196,Star Wars: Episode III - Revenge of the Sith,113000000,850000000,737000000
5427,The Hunger Games: Catching Fire,130000000,847423452,717423452
4413,The Twilight Saga: Breaking Dawn - Part 2,120000000,829000000,709000000
5431,The Hobbit: The Desolation of Smaug,250000000,958400000,708400000
634,The Hobbit: The Battle of the Five Armies,250000000,955119788,705119788
1923,Harry Potter and the Deathly Hallows: Part 1,250000000,954305868,704305868
1487,Transformers: Revenge of the Fallen,150000000,836297228,686297228
1389,Harry Potter and the Half-Blood Prince,250000000,933959197,683959197
3916,Spider-Man,139000000,821708551,682708551
9,Inside Out,175000000,853708609,678708609
1919,Inception,160000000,825500000,665500000
7387,Pirates of the Caribbean: At World's End,300000000,961000000,661000000

### these are the most profitable moives ever 

### but what are the factors that makes it succsessful?

### let's investigate the objective factors that effects it
#### company or cast

In [152]:
comp_rev = cost_rev_most.copy()
comp_rev = comp_rev.merge(data[['original_title', 'production_companies']], on='original_title')



comp_rev.head(50)

,original_title,budget,revenue,profit,production_companies
0,Avatar,237000000,2781505847,2544505847,Ingenious Film Partners|Twentieth Century Fox ...
1,Star Wars: The Force Awakens,200000000,2068178225,1868178225,Lucasfilm|Truenorth Productions|Bad Robot
2,Titanic,200000000,1845034188,1645034188,Paramount Pictures|Twentieth Century Fox Film ...
3,Titanic,200000000,1845034188,1645034188,American Zoetrope
4,Titanic,13000000,0,-13000000,Paramount Pictures|Twentieth Century Fox Film ...
5,Titanic,13000000,0,-13000000,American Zoetrope
6,Jurassic World,150000000,1513528810,1363528810,Universal Studios|Amblin Entertainment|Legenda...
7,Furious 7,190000000,1506249360,1316249360,Universal Pictures|Original Film|Media Rights ...
8,The Avengers,220000000,1519557910,1299557910,Marvel Studios
9,The Avengers,220000000,1519557910,1299557910,Jerry Weintraub Productions|Warner Bros.
10,The Avengers,60000000,48522832,-11477168,Marvel Studios
11,The Avengers,60000000,48522832,-11477168,Jerry Weintraub Productions|Warner Bros.
12,Harry Potter and the Deathly Hallows: Part 2,125000000,1327817822,1202817822,Warner Bros.|Heyday Films|Moving Picture Compa...
13,Avengers: Age of Ultron,280000000,1405035767,1125035767,Marvel Studios|Prime Focus|Revolution Sun Studios
14,Frozen,150000000,1274219009,1124219009,ArieScope Pictures|A Bigger Boat
15,Frozen,150000000,1274219009,1124219009,Walt Disney Pictures|Walt Disney Animation Stu...
16,Frozen,0,3065860,3065860,ArieScope Pictures|A Bigger Boat
17,Frozen,0,3065860,3065860,Walt Disney Pictures|Walt Disney Animation Stu...
18,The Net,22000000,1106279658,1084279658,Columbia Pictures
19,Minions,74000000,1156730962,1082730962,Universal Pictures|Illumination Entertainment
20,The Lord of the Rings: The Return of the King,94000000,1118888979,1024888979,WingNut Films|New Line Cinema
21,Iron Man 3,200000000,1215439994,1015439994,Marvel Studios
22,Transformers: Dark of the Moon,195000000,1123746996,928746996,Paramount Pictures|Di Bonaventura Pictures|Has...
23,Skyfall,200000000,1108561013,908561013,Columbia Pictures
24,Despicable Me 2,76000000,970761885,894761885,Universal Pictures|Illumination Entertainment
25,Pirates of the Caribbean: Dead Man's Chest,200000000,1065659812,865659812,Walt Disney Pictures|Jerry Bruckheimer Films|S...
26,Toy Story 3,200000000,1063171911,863171911,Walt Disney Pictures|Pixar Animation Studios
27,Jurassic Park,63000000,920100000,857100000,Universal Pictures|Amblin Entertainment
28,Harry Potter and the Philosopher's Stone,125000000,976475550,851475550,1492 Pictures|Warner Bros.|Heyday Films
29,The Lord of the Rings: The Two Towers,79000000,926287400,847287400,WingNut Films|New Line Cinema|The Saul Zaentz ...
30,The Dark Knight Rises,250000000,1081041287,831041287,Legendary Pictures|Warner Bros.|DC Entertainme...
31,Alice in Wonderland,200000000,1025467110,825467110,Walt Disney Pictures|Team Todd|Tim Burton Prod...
32,Alice in Wonderland,200000000,1025467110,825467110,NBC|Hallmark Entertainment
33,Alice in Wonderland,200000000,1025467110,825467110,NaN
34,Alice in Wonderland,0,0,0,Walt Disney Pictures|Team Todd|Tim Burton Prod...
35,Alice in Wonderland,0,0,0,NBC|Hallmark Entertainment
36,Alice in Wonderland,0,0,0,NaN
37,Alice in Wonderland,21000000,0,-21000000,Walt Disney Pictures|Team Todd|Tim Burton Prod...
38,Alice in Wonderland,21000000,0,-21000000,NBC|Hallmark Entertainment
39,Alice in Wonderland,21000000,0,-21000000,NaN
40,The Dark Knight,185000000,1001921825,816921825,DC Comics|Legendary Pictures|Warner Bros.|Syncopy
41,Star Wars: Episode I - The Phantom Menace,115000000,924317558,809317558,Lucasfilm
42,Ice Age: Dawn of the Dinosaurs,90000000,886686817,796686817,Blue Sky Studios|Twentieth Century Fox Animation
43,Harry Potter and the Order of the Phoenix,150000000,938212738,788212738,Cool Music|Warner Bros.|Heyday Films|Harry Pot...
44,E.T. the Extra-Terrestrial,10500000,792910554,782410554,Universal Pictures|Amblin Entertainment
45,Ice Age: Continental Drift,95000000,877244782,782244782,Blue Sky Studios|Twentieth Century Fox Animation
46,The Lord of the Rings: The Fellowship of the Ring,93000000,871368364,778368364,WingNut Films|New Line Cinema|The Saul Zaentz ...
47,Harry Potter and the Chamber of Secrets,100000000,876688482,776688482,1492 Pictures|Warner Bros.|Heyday Films|MIRACL...
48,Finding Nemo,94000000,864625978,770625978,Walt Disney Pictures|Pixar Animation Studios|D...
49,Shrek 2,150000000,919838758,769838758,DreamWorks SKG|Pacific Data Images (PDI)|Dream...

In [176]:
compnum = pd.DataFrame(comp_rev)
compnum['company_count'] = compnum.groupby('production_companies').cumcount() + 1
compnum_sorted = compnum.sort_values(by='company_count', ascending=False)


compnum.head(50)

,original_title,budget,revenue,profit,production_companies,company_count
0,Avatar,237000000,2781505847,2544505847,Ingenious Film Partners|Twentieth Century Fox ...,1.0
1,Star Wars: The Force Awakens,200000000,2068178225,1868178225,Lucasfilm|Truenorth Productions|Bad Robot,1.0
2,Titanic,200000000,1845034188,1645034188,Paramount Pictures|Twentieth Century Fox Film ...,1.0
3,Titanic,200000000,1845034188,1645034188,American Zoetrope,1.0
4,Titanic,13000000,0,-13000000,Paramount Pictures|Twentieth Century Fox Film ...,2.0
5,Titanic,13000000,0,-13000000,American Zoetrope,2.0
6,Jurassic World,150000000,1513528810,1363528810,Universal Studios|Amblin Entertainment|Legenda...,1.0
7,Furious 7,190000000,1506249360,1316249360,Universal Pictures|Original Film|Media Rights ...,1.0
8,The Avengers,220000000,1519557910,1299557910,Marvel Studios,1.0
9,The Avengers,220000000,1519557910,1299557910,Jerry Weintraub Productions|Warner Bros.,1.0
10,The Avengers,60000000,48522832,-11477168,Marvel Studios,2.0
11,The Avengers,60000000,48522832,-11477168,Jerry Weintraub Productions|Warner Bros.,2.0
12,Harry Potter and the Deathly Hallows: Part 2,125000000,1327817822,1202817822,Warner Bros.|Heyday Films|Moving Picture Compa...,1.0
13,Avengers: Age of Ultron,280000000,1405035767,1125035767,Marvel Studios|Prime Focus|Revolution Sun Studios,1.0
14,Frozen,150000000,1274219009,1124219009,ArieScope Pictures|A Bigger Boat,1.0
15,Frozen,150000000,1274219009,1124219009,Walt Disney Pictures|Walt Disney Animation Stu...,1.0
16,Frozen,0,3065860,3065860,ArieScope Pictures|A Bigger Boat,2.0
17,Frozen,0,3065860,3065860,Walt Disney Pictures|Walt Disney Animation Stu...,2.0
18,The Net,22000000,1106279658,1084279658,Columbia Pictures,1.0
19,Minions,74000000,1156730962,1082730962,Universal Pictures|Illumination Entertainment,1.0
20,The Lord of the Rings: The Return of the King,94000000,1118888979,1024888979,WingNut Films|New Line Cinema,1.0
21,Iron Man 3,200000000,1215439994,1015439994,Marvel Studios,3.0
22,Transformers: Dark of the Moon,195000000,1123746996,928746996,Paramount Pictures|Di Bonaventura Pictures|Has...,1.0
23,Skyfall,200000000,1108561013,908561013,Columbia Pictures,2.0
24,Despicable Me 2,76000000,970761885,894761885,Universal Pictures|Illumination Entertainment,2.0
25,Pirates of the Caribbean: Dead Man's Chest,200000000,1065659812,865659812,Walt Disney Pictures|Jerry Bruckheimer Films|S...,1.0
26,Toy Story 3,200000000,1063171911,863171911,Walt Disney Pictures|Pixar Animation Studios,1.0
27,Jurassic Park,63000000,920100000,857100000,Universal Pictures|Amblin Entertainment,1.0
28,Harry Potter and the Philosopher's Stone,125000000,976475550,851475550,1492 Pictures|Warner Bros.|Heyday Films,1.0
29,The Lord of the Rings: The Two Towers,79000000,926287400,847287400,WingNut Films|New Line Cinema|The Saul Zaentz ...,1.0
30,The Dark Knight Rises,250000000,1081041287,831041287,Legendary Pictures|Warner Bros.|DC Entertainme...,1.0
31,Alice in Wonderland,200000000,1025467110,825467110,Walt Disney Pictures|Team Todd|Tim Burton Prod...,1.0
32,Alice in Wonderland,200000000,1025467110,825467110,NBC|Hallmark Entertainment,1.0
33,Alice in Wonderland,200000000,1025467110,825467110,NaN,NaN
34,Alice in Wonderland,0,0,0,Walt Disney Pictures|Team Todd|Tim Burton Prod...,2.0
35,Alice in Wonderland,0,0,0,NBC|Hallmark Entertainment,2.0
36,Alice in Wonderland,0,0,0,NaN,NaN
37,Alice in Wonderland,21000000,0,-21000000,Walt Disney Pictures|Team Todd|Tim Burton Prod...,3.0
38,Alice in Wonderland,21000000,0,-21000000,NBC|Hallmark Entertainment,3.0
39,Alice in Wonderland,21000000,0,-21000000,NaN,NaN
40,The Dark Knight,185000000,1001921825,816921825,DC Comics|Legendary Pictures|Warner Bros.|Syncopy,1.0
41,Star Wars: Episode I - The Phantom Menace,115000000,924317558,809317558,Lucasfilm,1.0
42,Ice Age: Dawn of the Dinosaurs,90000000,886686817,796686817,Blue Sky Studios|Twentieth Century Fox Animation,1.0
43,Harry Potter and the Order of the Phoenix,150000000,938212738,788212738,Cool Music|Warner Bros.|Heyday Films|Harry Pot...,1.0
44,E.T. the Extra-Terrestrial,10500000,792910554,782410554,Universal Pictures|Amblin Entertainment,2.0
45,Ice Age: Continental Drift,95000000,877244782,782244782,Blue Sky Studios|Twentieth Century Fox Animation,2.0
46,The Lord of the Rings: The Fellowship of the Ring,93000000,871368364,778368364,WingNut Films|New Line Cinema|The Saul Zaentz ...,2.0
47,Harry Potter and the Chamber of Secrets,100000000,876688482,776688482,1492 Pictures|Warner Bros.|Heyday Films|MIRACL...,1.0
48,Finding Nemo,94000000,864625978,770625978,Walt Disney Pictures|Pixar Animation Studios|D...,1.0
49,Shrek 2,150000000,919838758,769838758,DreamWorks SKG|Pacific Data Images (PDI)|Dream...,1.0

## although the data is inaccurate theres a big inication that production of corprate companies are involved in succsession

### but how many of them were involved in the top 50 moives

In [221]:
comp_copy = cost_rev.copy()
comp_copy = comp_copy.merge(data[['original_title', 'production_companies']], on='original_title')
comp_copy = comp_copy.sort_values(by='revenue', ascending=False)
comp_copy_filtered = comp_copy[comp_copy['revenue'] > 960000000]


disney_count = (comp_copy_filtered['production_companies'].str.contains('Disney', case=False)).sum()
uni_count = (comp_copy_filtered['production_companies'].str.contains('universal', case=False)).sum()
marvel_count = (comp_copy_filtered['production_companies'].str.contains('marvel', case=False)).sum()
warner_count = (comp_copy_filtered['production_companies'].str.contains('warner', case=False)).sum()
warner_count = (comp_copy_filtered['production_companies'].str.contains('warner', case=False)).sum()
para_count = (comp_copy_filtered['production_companies'].str.contains('paramount', case=False)).sum()
col_count = (comp_copy_filtered['production_companies'].str.contains('columbia', case=False)).sum()


print(f'The word "Disney" appears {disney_count} times in the production companies.')
print(f'The word "universal" appears {uni_count} times in the production companies.')
print(f'The word "marvel" appears {marvel_count} times in the production companies.')
print(f'The word "warner bros" appears {warner_count} times in the production companies.')
print(f'The word "paramount pictures" appears {para_count} times in the production companies.')
print(f'The word "columbia pictures" appears {col_count} times in the production companies.')
comp_copy_filtered.head(50)

The word "Disney" appears 6 times in the production companies.
The word "universal" appears 4 times in the production companies.
The word "marvel" appears 3 times in the production companies.
The word "warner bros" appears 5 times in the production companies.
The word "paramount pictures" appears 2 times in the production companies.
The word "columbia pictures" appears 2 times in the production companies.

,original_title,budget,revenue,profit,production_companies
1605,Avatar,237000000,2781505847,2544505847,Ingenious Film Partners|Twentieth Century Fox ...
3,Star Wars: The Force Awakens,200000000,2068178225,1868178225,Lucasfilm|Truenorth Productions|Bad Robot
5860,Titanic,200000000,1845034188,1645034188,American Zoetrope
5859,Titanic,200000000,1845034188,1645034188,Paramount Pictures|Twentieth Century Fox Film ...
4913,The Avengers,220000000,1519557910,1299557910,Marvel Studios
4914,The Avengers,220000000,1519557910,1299557910,Jerry Weintraub Productions|Warner Bros.
0,Jurassic World,150000000,1513528810,1363528810,Universal Studios|Amblin Entertainment|Legenda...
4,Furious 7,190000000,1506249360,1316249360,Universal Pictures|Original Film|Media Rights ...
17,Avengers: Age of Ultron,280000000,1405035767,1125035767,Marvel Studios|Prime Focus|Revolution Sun Studios
3839,Harry Potter and the Deathly Hallows: Part 2,125000000,1327817822,1202817822,Warner Bros.|Heyday Films|Moving Picture Compa...
2473,Frozen,150000000,1274219009,1124219009,Walt Disney Pictures|Walt Disney Animation Stu...
2472,Frozen,150000000,1274219009,1124219009,ArieScope Pictures|A Bigger Boat
6066,Iron Man 3,200000000,1215439994,1015439994,Marvel Studios
11,Minions,74000000,1156730962,1082730962,Universal Pictures|Illumination Entertainment
4018,Transformers: Dark of the Moon,195000000,1123746996,928746996,Paramount Pictures|Di Bonaventura Pictures|Has...
5567,The Lord of the Rings: The Return of the King,94000000,1118888979,1024888979,WingNut Films|New Line Cinema
4920,Skyfall,200000000,1108561013,908561013,Columbia Pictures
8837,The Net,22000000,1106279658,1084279658,Columbia Pictures
4918,The Dark Knight Rises,250000000,1081041287,831041287,Legendary Pictures|Warner Bros.|DC Entertainme...
7251,Pirates of the Caribbean: Dead Man's Chest,200000000,1065659812,865659812,Walt Disney Pictures|Jerry Bruckheimer Films|S...
2258,Toy Story 3,200000000,1063171911,863171911,Walt Disney Pictures|Pixar Animation Studios
2242,Alice in Wonderland,200000000,1025467110,825467110,NBC|Hallmark Entertainment
2243,Alice in Wonderland,200000000,1025467110,825467110,NaN
2241,Alice in Wonderland,200000000,1025467110,825467110,Walt Disney Pictures|Team Todd|Tim Burton Prod...
3840,Pirates of the Caribbean: On Stranger Tides,380000000,1021683000,641683000,Walt Disney Pictures|Jerry Bruckheimer Films|M...
4922,The Hobbit: An Unexpected Journey,250000000,1017003568,767003568,WingNut Films|New Line Cinema|Metro-Goldwyn-Ma...
3296,The Dark Knight,185000000,1001921825,816921825,DC Comics|Legendary Pictures|Warner Bros.|Syncopy
3040,Harry Potter and the Philosopher's Stone,125000000,976475550,851475550,1492 Pictures|Warner Bros.|Heyday Films
6075,Despicable Me 2,76000000,970761885,894761885,Universal Pictures|Illumination Entertainment
8135,Pirates of the Caribbean: At World's End,300000000,961000000,661000000,Walt Disney Pictures|Jerry Bruckheimer Films|S...

## as shown disney takes part in most top grossing movies 
### but does it reflect on fan admiration

In [283]:
pop_count = data[['original_title', 'revenue', 'budget','popularity', 'vote_count', 'vote_average','profit' ]]
data['profit'] = pop_count['revenue'] - pop_count['budget']

profit_min = 660000000
filtered_counted = pop_count[pop_count['profit'] > profit_min]


filtered_counted = filtered_counted.sort_values(by=['vote_average', 'profit'], ascending=[False, False])


filtered_counted.head(50)

,original_title,revenue,budget,popularity,vote_count,vote_average,profit
2875,The Dark Knight,1001921825,185000000,8.466668,8432,8.1,816921825
9,Inside Out,853708609,175000000,6.326804,3935,8.0,678708609
4949,The Lord of the Rings: The Return of the King,1118888979,94000000,7.122455,5636,7.9,1024888979
1329,Star Wars,775398007,11000000,12.037933,4428,7.9,764398007
1919,Inception,825500000,160000000,9.363643,9767,7.9,665500000
3911,The Lord of the Rings: The Two Towers,926287400,79000000,8.095275,5114,7.8,847287400
2633,The Lord of the Rings: The Fellowship of the Ring,871368364,93000000,8.575419,6079,7.8,778368364
3374,Harry Potter and the Deathly Hallows: Part 2,1327817822,125000000,5.711315,3750,7.7,1202817822
4180,The Lion King,788241776,45000000,4.782688,3489,7.7,743241776
5431,The Hobbit: The Desolation of Smaug,958400000,250000000,4.310786,2952,7.6,708400000
3,Star Wars: The Force Awakens,2068178225,200000000,11.173104,5292,7.5,1868178225
5422,Frozen,1274219009,150000000,6.112766,3369,7.5,1124219009
1930,Toy Story 3,1063171911,200000000,2.711136,2924,7.5,863171911
4363,The Dark Knight Rises,1081041287,250000000,6.591277,6723,7.5,831041287
14,Avengers: Age of Ultron,1405035767,280000000,5.944927,4304,7.4,1125035767
10223,Jurassic Park,920100000,63000000,2.204926,3169,7.4,857100000
4955,Finding Nemo,864625978,94000000,3.440519,3692,7.4,770625978
5427,The Hunger Games: Catching Fire,847423452,130000000,4.921275,4269,7.4,717423452
1923,Harry Potter and the Deathly Hallows: Part 1,954305868,250000000,4.840588,3467,7.4,704305868
5231,Titanic,1845034188,200000000,4.355219,4654,7.3,1645034188
4,Furious 7,1506249360,190000000,9.335014,2947,7.3,1316249360
4361,The Avengers,1519557910,220000000,7.637767,8903,7.3,1299557910
6190,Harry Potter and the Goblet of Fire,895921036,150000000,5.939927,3406,7.3,745921036
1389,Harry Potter and the Half-Blood Prince,933959197,250000000,5.076472,3220,7.3,683959197
2634,Harry Potter and the Philosopher's Stone,976475550,125000000,8.021423,4265,7.2,851475550
7388,Harry Potter and the Order of the Phoenix,938212738,150000000,4.878162,3382,7.2,788212738
8889,E.T. the Extra-Terrestrial,792910554,10500000,2.900556,1830,7.2,782410554
3912,Harry Potter and the Chamber of Secrets,876688482,100000000,6.012584,3458,7.2,776688482
1386,Avatar,2781505847,237000000,9.432768,8458,7.1,2544505847
634,The Hobbit: The Battle of the Five Armies,955119788,250000000,10.174599,3110,7.1,705119788
5434,Despicable Me 2,970761885,76000000,3.928789,3436,7.0,894761885
6196,Star Wars: Episode III - Revenge of the Sith,850000000,113000000,3.457537,2629,7.0,737000000
5425,Iron Man 3,1215439994,200000000,4.946136,6882,6.9,1015439994
4367,The Hobbit: An Unexpected Journey,1017003568,250000000,4.218933,6417,6.9,767003568
4365,Skyfall,1108561013,200000000,5.603587,6137,6.8,908561013
6555,Pirates of the Caribbean: Dead Man's Chest,1065659812,200000000,4.205992,3181,6.8,865659812
7387,Pirates of the Caribbean: At World's End,961000000,300000000,4.965391,2626,6.8,661000000
8457,Independence Day,816969268,75000000,4.480733,2000,6.6,741969268
3916,Spider-Man,821708551,139000000,3.241129,3170,6.6,682708551
0,Jurassic World,1513528810,150000000,32.985763,5562,6.5,1363528810
8,Minions,1156730962,74000000,7.404165,2893,6.5,1082730962
6977,Shrek 2,919838758,150000000,2.191033,1676,6.5,769838758
1396,Ice Age: Dawn of the Dinosaurs,886686817,90000000,3.154914,1392,6.4,796686817
1921,Alice in Wonderland,1025467110,200000000,5.572950,2853,6.3,825467110
2412,Star Wars: Episode I - The Phantom Menace,924317558,115000000,3.526029,2823,6.3,809317558
4375,Ice Age: Continental Drift,877244782,95000000,3.135776,1920,6.2,782244782
3522,Transformers: Dark of the Moon,1123746996,195000000,0.760503,2456,6.1,928746996
4413,The Twilight Saga: Breaking Dawn - Part 2,829000000,120000000,1.586368,1668,6.1,709000000
1487,Transformers: Revenge of the Fallen,836297228,150000000,0.813323,2230,6.0,686297228
8094,The Net,1106279658,22000000,1.136610,201,5.6,1084279658

In [292]:
 cost_rev_most_copy_third = cost_rev_most.copy()
cost_rev_most_copy_third['vote_average'] = data['vote_average']
cost_rev_most_copy_third.head(50)

,original_title,budget,revenue,profit,vote_average
1386,Avatar,237000000,2781505847,2544505847,7.1
3,Star Wars: The Force Awakens,200000000,2068178225,1868178225,7.5
5231,Titanic,200000000,1845034188,1645034188,7.3
0,Jurassic World,150000000,1513528810,1363528810,6.5
4,Furious 7,190000000,1506249360,1316249360,7.3
4361,The Avengers,220000000,1519557910,1299557910,7.3
3374,Harry Potter and the Deathly Hallows: Part 2,125000000,1327817822,1202817822,7.7
14,Avengers: Age of Ultron,280000000,1405035767,1125035767,7.4
5422,Frozen,150000000,1274219009,1124219009,7.5
8094,The Net,22000000,1106279658,1084279658,5.6
8,Minions,74000000,1156730962,1082730962,6.5
4949,The Lord of the Rings: The Return of the King,94000000,1118888979,1024888979,7.9
5425,Iron Man 3,200000000,1215439994,1015439994,6.9
3522,Transformers: Dark of the Moon,195000000,1123746996,928746996,6.1
4365,Skyfall,200000000,1108561013,908561013,6.8
5434,Despicable Me 2,76000000,970761885,894761885,7.0
6555,Pirates of the Caribbean: Dead Man's Chest,200000000,1065659812,865659812,6.8
1930,Toy Story 3,200000000,1063171911,863171911,7.5
10223,Jurassic Park,63000000,920100000,857100000,7.4
2634,Harry Potter and the Philosopher's Stone,125000000,976475550,851475550,7.2
3911,The Lord of the Rings: The Two Towers,79000000,926287400,847287400,7.8
4363,The Dark Knight Rises,250000000,1081041287,831041287,7.5
1921,Alice in Wonderland,200000000,1025467110,825467110,6.3
2875,The Dark Knight,185000000,1001921825,816921825,8.1
2412,Star Wars: Episode I - The Phantom Menace,115000000,924317558,809317558,6.3
1396,Ice Age: Dawn of the Dinosaurs,90000000,886686817,796686817,6.4
7388,Harry Potter and the Order of the Phoenix,150000000,938212738,788212738,7.2
8889,E.T. the Extra-Terrestrial,10500000,792910554,782410554,7.2
4375,Ice Age: Continental Drift,95000000,877244782,782244782,6.2
2633,The Lord of the Rings: The Fellowship of the Ring,93000000,871368364,778368364,7.8
3912,Harry Potter and the Chamber of Secrets,100000000,876688482,776688482,7.2
4955,Finding Nemo,94000000,864625978,770625978,7.4
6977,Shrek 2,150000000,919838758,769838758,6.5
4367,The Hobbit: An Unexpected Journey,250000000,1017003568,767003568,6.9
1329,Star Wars,11000000,775398007,764398007,7.9
6190,Harry Potter and the Goblet of Fire,150000000,895921036,745921036,7.3
4180,The Lion King,45000000,788241776,743241776,7.7
8457,Independence Day,75000000,816969268,741969268,6.6
6196,Star Wars: Episode III - Revenge of the Sith,113000000,850000000,737000000,7.0
5427,The Hunger Games: Catching Fire,130000000,847423452,717423452,7.4
4413,The Twilight Saga: Breaking Dawn - Part 2,120000000,829000000,709000000,6.1
5431,The Hobbit: The Desolation of Smaug,250000000,958400000,708400000,7.6
634,The Hobbit: The Battle of the Five Armies,250000000,955119788,705119788,7.1
1923,Harry Potter and the Deathly Hallows: Part 1,250000000,954305868,704305868,7.4
1487,Transformers: Revenge of the Fallen,150000000,836297228,686297228,6.0
1389,Harry Potter and the Half-Blood Prince,250000000,933959197,683959197,7.3
3916,Spider-Man,139000000,821708551,682708551,6.6
9,Inside Out,175000000,853708609,678708609,8.0
1919,Inception,160000000,825500000,665500000,7.9
7387,Pirates of the Caribbean: At World's End,300000000,961000000,661000000,6.8

# in comparison success around people don't equal success in profit